---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    type: front-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front
  template:
    metadata:
      labels: 
        type: front
    spec: 
      containers:
        - name: front
          image: minamaher0/frontend-nodejs:ingress1
          ports: 
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    type: back-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      type: back
  template:
    metadata:
      labels: 
        type: back
    spec: 
      containers:
        - name: back
          image: kareemelkasaby/badreads-backend:latest
          ports: 
            - containerPort: 4000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    type: database-dep
spec:
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      labels: 
        type: database
    spec: 
      containers:
        - name: database
          image: mongo:4.2.8
          env:
            - name: MONGO_INITDB_DATABASE
              value: "admin"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "123456"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    type: back

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    type: front

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
  selector:
    type: database

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: front.minamaher.codes
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-svc
          servicePort: 80
  - host: back.minamaher.codes
    http:
      paths:
      - path: /
        backend:
          serviceName: backend-svc
          servicePort: 80